---
# [WARNING]: Could not find aptitude. Using apt-get instead fix
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes
- name: "Install required packages on Ubuntu"
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - python-pip
      - python-virtualenv
      - rancid

- name: "Install virtualenv using Python 2.7"
  pip:
    virtualenv: "/home/vagrant/ansible_27/venv"
    requirements: /vagrant/provisioning/req27.txt
    virtualenv_python: python2.7

- name: "Install virtualenv using Python 3.5"
  pip:
    virtualenv: "/home/vagrant/ansible_35/venv"
    requirements: /vagrant/provisioning/req35.txt
    virtualenv_python: python3.5
  when: " ansible_os_family == 'Debian' and ansible_distribution in ['Ubuntu'] and ansible_distribution_major_version in ['16'] and ansible_distribution_version in ['16.04']"

- name: "Install virtualenv using Python 3.7"
  pip:
    virtualenv: "/home/vagrant/ansible_37/venv"
    requirements: /vagrant/provisioning/req37.txt
    virtualenv_python: python3.7
  when: "  ansible_os_family == 'Debian' and ansible_distribution in ['Ubuntu'] and ansible_distribution_major_version in ['19'] and ansible_distribution_version in ['19.04']"
