---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
- name: "Install caldera"
  gather_facts: true
  hosts: vg-caldera-79
  become: yes
  roles:
    - virtualcaldera
